version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: cruise_app
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql
    networks:
      - cruise_network

  nginx:
    image: nginx:alpine
    container_name: cruise_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - cruise_network

  mysql:
    image: mysql:8.0
    container_name: cruise_mysql
    restart: unless-stopped
    environment:
        MYSQL_DATABASE: cruise_db
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: secret
        MYSQL_USER: cruise_user
        MYSQL_CHARSET: utf8mb4
        MYSQL_COLLATION: utf8mb4_unicode_ci
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
        - "3307:3306"
    volumes:
        - cruise_mysql_data:/var/lib/mysql
        - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
        - cruise_network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: cruise_node
    volumes:
      - .:/var/www
    working_dir: /var/www
    networks:
      - cruise_network

volumes:
  cruise_mysql_data:

networks:
  cruise_network:
    driver: bridge
